python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Airlines  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Airlines  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Airlines  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d christine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d christine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d christine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d shuttle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d shuttle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d shuttle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d car  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d car  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d car  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d credit  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d credit  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d credit  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d connect  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d connect  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d connect  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d sylvine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d sylvine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d volkert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d volkert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d volkert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d MiniBooNE  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d MiniBooNE  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d MiniBooNE  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Jannis  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Jannis  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Jannis  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d mfeat  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d mfeat  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d mfeat  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d jungle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d jungle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d jungle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d jasmine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d fabert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d fabert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d fabert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d segment  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d segment  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d segment  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d cnae  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d cnae  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d cnae  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d kc1  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d kc1  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d kc1  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d kr  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d kr  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d kr  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Albert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Albert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Albert  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d APSFailure  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d APSFailure  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d APSFailure  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d bank  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d bank  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d bank  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d nomao  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d nomao  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d nomao  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d numerai28  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d numerai28  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d numerai28  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d phoneme  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d phoneme  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d phoneme  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Helena  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Helena  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Helena  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d KDDCup09  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d KDDCup09  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d KDDCup09  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d adult  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d adult  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d adult  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Amazon  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Amazon  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Amazon  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d vehicle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d vehicle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d vehicle  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d blood  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d blood  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d blood  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Australian  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d jasmine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d jasmine  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d higgs  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d higgs  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d higgs  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 0 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Australian  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 1 
python test/test_automl_exp.py  -t 0.1 -l xgb_flaml_woinit -d Australian  -m BlendSearchNoDiscount -total_pu 4 -trial_pu 1  -r 2 